
apiVersion: v1
kind: Service
metadata:
  name: grpc-server-service
spec:
  type: LoadBalancer
  ports:
    - port: 19003
      targetPort: 19003
      protocol: TCP
      name: grpc
  selector:
    # podのラベルを指定
    app: server
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grpc-server-deployment
spec:
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: shinofara/golang-grpc-example-server:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 19003
            name: grpc
