// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example.proto

/*
Package grpc is a generated protocol buffer package.

It is generated from these files:
	example.proto

It has these top-level messages:
	GetDataRequest
	GetDataResponse
*/
package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc1 "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetDataRequest struct {
	Id   int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Wait int32 `protobuf:"varint,2,opt,name=wait" json:"wait,omitempty"`
}

func (m *GetDataRequest) Reset()                    { *m = GetDataRequest{} }
func (m *GetDataRequest) String() string            { return proto.CompactTextString(m) }
func (*GetDataRequest) ProtoMessage()               {}
func (*GetDataRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetDataRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetDataRequest) GetWait() int32 {
	if m != nil {
		return m.Wait
	}
	return 0
}

type GetDataResponse struct {
	Data string `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
}

func (m *GetDataResponse) Reset()                    { *m = GetDataResponse{} }
func (m *GetDataResponse) String() string            { return proto.CompactTextString(m) }
func (*GetDataResponse) ProtoMessage()               {}
func (*GetDataResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetDataResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*GetDataRequest)(nil), "grpc.GetDataRequest")
	proto.RegisterType((*GetDataResponse)(nil), "grpc.GetDataResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc1.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc1.SupportPackageIsVersion4

// Client API for Example service

type ExampleClient interface {
	GetData(ctx context.Context, in *GetDataRequest, opts ...grpc1.CallOption) (*GetDataResponse, error)
}

type exampleClient struct {
	cc *grpc1.ClientConn
}

func NewExampleClient(cc *grpc1.ClientConn) ExampleClient {
	return &exampleClient{cc}
}

func (c *exampleClient) GetData(ctx context.Context, in *GetDataRequest, opts ...grpc1.CallOption) (*GetDataResponse, error) {
	out := new(GetDataResponse)
	err := grpc1.Invoke(ctx, "/grpc.Example/GetData", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Example service

type ExampleServer interface {
	GetData(context.Context, *GetDataRequest) (*GetDataResponse, error)
}

func RegisterExampleServer(s *grpc1.Server, srv ExampleServer) {
	s.RegisterService(&_Example_serviceDesc, srv)
}

func _Example_GetData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleServer).GetData(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Example/GetData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleServer).GetData(ctx, req.(*GetDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Example_serviceDesc = grpc1.ServiceDesc{
	ServiceName: "grpc.Example",
	HandlerType: (*ExampleServer)(nil),
	Methods: []grpc1.MethodDesc{
		{
			MethodName: "GetData",
			Handler:    _Example_GetData_Handler,
		},
	},
	Streams:  []grpc1.StreamDesc{},
	Metadata: "example.proto",
}

func init() { proto.RegisterFile("example.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 151 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0xad, 0x48, 0xcc,
	0x2d, 0xc8, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x49, 0x2f, 0x2a, 0x48, 0x56,
	0x32, 0xe1, 0xe2, 0x73, 0x4f, 0x2d, 0x71, 0x49, 0x2c, 0x49, 0x0c, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d,
	0x2e, 0x11, 0xe2, 0xe3, 0x62, 0xca, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0d, 0x62, 0xca,
	0x4c, 0x11, 0x12, 0xe2, 0x62, 0x29, 0x4f, 0xcc, 0x2c, 0x91, 0x60, 0x02, 0x8b, 0x80, 0xd9, 0x4a,
	0xaa, 0x5c, 0xfc, 0x70, 0x5d, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x20, 0x65, 0x29, 0x89, 0x25,
	0x89, 0x60, 0x8d, 0x9c, 0x41, 0x60, 0xb6, 0x91, 0x33, 0x17, 0xbb, 0x2b, 0xc4, 0x4e, 0x21, 0x0b,
	0x2e, 0x76, 0xa8, 0x0e, 0x21, 0x11, 0x3d, 0x90, 0xcd, 0x7a, 0xa8, 0xd6, 0x4a, 0x89, 0xa2, 0x89,
	0x42, 0x8c, 0x55, 0x62, 0x48, 0x62, 0x03, 0x3b, 0xd7, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xa8,
	0x1a, 0x34, 0x05, 0xbf, 0x00, 0x00, 0x00,
}
